version: '3'
services:
  backend:
    image: your-dockerhub-username/courses-api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: your-dockerhub-username/courses-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres
    environment:
      POSTGRES_USER: your-db-user
      POSTGRES_PASSWORD: your-db-password
